# Generated by Django 4.1.7 on 2023-03-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_black', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminBlackSetting',
        ),
    ]
