# Generated by Django 4.0.1 on 2023-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_alter_historicalusersdb_code_alter_usersdb_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusersdb',
            name='code',
            field=models.SlugField(help_text='Código Único (Usuario-Conexion-Compania-BaseDatos)', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='historicalusersdb',
            name='name',
            field=models.CharField(help_text='Nombre de la Base de Datos', max_length=100, verbose_name='Base de Datos'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='code',
            field=models.SlugField(help_text='Código Único (Usuario-Conexion-Compania-BaseDatos)', unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usersdb',
            name='name',
            field=models.CharField(help_text='Nombre de la Base de Datos', max_length=100, verbose_name='Base de Datos'),
        ),
    ]
